# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Willing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Willing

  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  # Add the pods for the Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift', '~> 7.0-beta'
  pod 'DLRadioButton', '~> 1.4'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'

end
